# nw-omarchy bspwm colors — generated by omarchy-theme-set-templates.
# Sourced from bspwmrc AFTER the static fallback colors so these win.
bspc config focused_border_color    "{{ accent }}"
bspc config normal_border_color     "{{ color8 }}"
bspc config presel_feedback_color   "{{ accent }}"
