# nw-omarchy dunst config — generated by omarchy-theme-set-templates.
# Symlinked from ~/.config/dunst/dunstrc. dunst picks up new colors via
# nw-omarchy-dunst-watch (inotify on theme.name → SIGTERM + relaunch).

[global]
    monitor             = 0
    follow              = mouse
    width               = 360
    height              = (0, 200)
    origin              = top-right
    offset              = 16x52
    notification_limit  = 5
    progress_bar        = true
    progress_bar_height = 6
    indicate_hidden     = true
    transparency        = 0
    separator_height    = 2
    padding             = 12
    horizontal_padding  = 16
    text_icon_padding   = 8
    frame_width         = 2
    frame_color         = "{{ accent }}"
    separator_color     = frame
    sort                = yes
    font                = JetBrainsMono Nerd Font Mono 10
    line_height         = 0
    markup              = full
    format              = "<b>%s</b>\n%b"
    alignment           = left
    vertical_alignment  = center
    show_age_threshold  = 60
    ellipsize           = middle
    ignore_newline      = no
    stack_duplicates    = true
    show_indicators     = no
    icon_position       = left
    min_icon_size       = 0
    max_icon_size       = 64
    enable_recursive_icon_lookup = true
    icon_theme          = "Papirus-Dark, Adwaita"
    sticky_history      = yes
    history_length      = 32
    browser             = /usr/bin/xdg-open
    always_run_script   = true
    title               = Dunst
    class               = Dunst
    corner_radius       = 8
    ignore_dbusclose    = false
    force_xwayland      = false
    force_xinerama      = false
    mouse_left_click    = close_current
    mouse_middle_click  = do_action, close_current
    mouse_right_click   = close_all

[urgency_low]
    background = "{{ background }}"
    foreground = "{{ foreground }}"
    timeout    = 5

[urgency_normal]
    background = "{{ background }}"
    foreground = "{{ foreground }}"
    timeout    = 8

[urgency_critical]
    background  = "{{ background }}"
    foreground  = "{{ color1 }}"
    frame_color = "{{ color1 }}"
    timeout     = 0
