; nw-omarchy polybar palette — generated by omarchy-theme-set-templates.
; Included by ~/.local/share/nw-omarchy/default/polybar/config.ini.
[colors]
background     = {{ background }}
background-alt = {{ color0 }}
foreground     = {{ foreground }}
primary        = {{ accent }}
secondary      = {{ color2 }}
alert          = {{ color1 }}
disabled       = {{ color8 }}
