/* nw-omarchy rofi palette — generated by omarchy-theme-set-templates.
 * Imported by ~/.local/share/nw-omarchy/default/rofi/config.rasi. */
* {
    bg:          {{ background }};
    bg-alt:      {{ color0 }};
    fg:          {{ foreground }};
    fg-alt:      {{ color7 }};
    primary:     {{ accent }};
    selected:    {{ selection_background }};
    selected-fg: {{ selection_foreground }};
    border:      {{ accent }};
    urgent:      {{ color1 }};
    disabled:    {{ color8 }};
}
